/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 1969-12-31 23:59:59 UTC)
 * on 2023-08-04 at 10:37:28 UTC 
 * Modify at your own risk.
 */

package com.uwetrottmann.seriesguide.backend.shows.model;

/**
 * Model definition for KeyObject.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the shows. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class KeyObject extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String kind;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private KeyObject parent;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key raw;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private KeyObject root;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("string")
  private java.lang.String string__;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public KeyObject setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKind() {
    return kind;
  }

  /**
   * @param kind kind or {@code null} for none
   */
  public KeyObject setKind(java.lang.String kind) {
    this.kind = kind;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public KeyObject setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public KeyObject getParent() {
    return parent;
  }

  /**
   * @param parent parent or {@code null} for none
   */
  public KeyObject setParent(KeyObject parent) {
    this.parent = parent;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getRaw() {
    return raw;
  }

  /**
   * @param raw raw or {@code null} for none
   */
  public KeyObject setRaw(Key raw) {
    this.raw = raw;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public KeyObject getRoot() {
    return root;
  }

  /**
   * @param root root or {@code null} for none
   */
  public KeyObject setRoot(KeyObject root) {
    this.root = root;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getString() {
    return string__;
  }

  /**
   * @param string__ string__ or {@code null} for none
   */
  public KeyObject setString(java.lang.String string__) {
    this.string__ = string__;
    return this;
  }

  @Override
  public KeyObject set(String fieldName, Object value) {
    return (KeyObject) super.set(fieldName, value);
  }

  @Override
  public KeyObject clone() {
    return (KeyObject) super.clone();
  }

}
