# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    working_directory: ~/SeriesGuide

    docker:
      - image: circleci/android:api-28-alpha

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          name: Assemble
          command: ./gradlew assembleDebug

      - run:
          name: Run Tests
          command: ./gradlew :app:test
      - store_test_results:
          path: app/build/test-results

      - run:
          name: Run Lint
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports/lint-results.html
          destination: lint-results-app.html
      - store_artifacts:
          path: api/build/reports/lint-results.html
          destination: lint-results-api.html
      - store_artifacts:
          path: libraries/drag-sort-listview/build/reports/lint-results.html
          destination: lint-results-drag-sort-listview.html
      - store_artifacts:
          path: libraries/stickygridheaders/build/reports/lint-results.html
          destination: lint-results-stickygridheaders.html

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
