blank_issues_enabled: true
contact_links:
  - name: Ask a question or suggest something
    url: https://discuss.seriesgui.de/
    about: Please use the community forum to ask questions or suggest something!
