// automatically generated by the FlatBuffers compiler, do not modify

package com.battlelancer.seriesguide.jobs;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class EpisodeInfo extends Table {
  public static EpisodeInfo getRootAsEpisodeInfo(ByteBuffer _bb) { return getRootAsEpisodeInfo(_bb, new EpisodeInfo()); }
  public static EpisodeInfo getRootAsEpisodeInfo(ByteBuffer _bb, EpisodeInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public EpisodeInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int season() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int number() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createEpisodeInfo(FlatBufferBuilder builder,
      int season,
      int number) {
    builder.startObject(2);
    EpisodeInfo.addNumber(builder, number);
    EpisodeInfo.addSeason(builder, season);
    return EpisodeInfo.endEpisodeInfo(builder);
  }

  public static void startEpisodeInfo(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addSeason(FlatBufferBuilder builder, int season) { builder.addInt(0, season, 0); }
  public static void addNumber(FlatBufferBuilder builder, int number) { builder.addInt(1, number, 0); }
  public static int endEpisodeInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

