// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright © 2023 Uwe Trottmann <uwe@uwetrottmann.com>
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 1969-12-31 23:59:59 UTC)
 * on 2023-08-04 at 10:37:20 UTC 
 * Modify at your own risk.
 */

package com.uwetrottmann.seriesguide.backend.episodes.model;

/**
 * Model definition for EpisodeList.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the episodes. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class EpisodeList extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cursor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Episode> episodes;

  static {
    // hack to force ProGuard to consider Episode used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(Episode.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer showTvdbId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCursor() {
    return cursor;
  }

  /**
   * @param cursor cursor or {@code null} for none
   */
  public EpisodeList setCursor(java.lang.String cursor) {
    this.cursor = cursor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Episode> getEpisodes() {
    return episodes;
  }

  /**
   * @param episodes episodes or {@code null} for none
   */
  public EpisodeList setEpisodes(java.util.List<Episode> episodes) {
    this.episodes = episodes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getShowTvdbId() {
    return showTvdbId;
  }

  /**
   * @param showTvdbId showTvdbId or {@code null} for none
   */
  public EpisodeList setShowTvdbId(java.lang.Integer showTvdbId) {
    this.showTvdbId = showTvdbId;
    return this;
  }

  @Override
  public EpisodeList set(String fieldName, Object value) {
    return (EpisodeList) super.set(fieldName, value);
  }

  @Override
  public EpisodeList clone() {
    return (EpisodeList) super.clone();
  }

}
