/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 1969-12-31 23:59:59 UTC)
 * on 2023-08-04 at 10:37:20 UTC 
 * Modify at your own risk.
 */

package com.uwetrottmann.seriesguide.backend.episodes.model;

/**
 * Model definition for SgCloudEpisode.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the episodes. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SgCloudEpisode extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime createdAt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer episodeNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isInCollection;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer plays;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer seasonNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer showTmdbId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime updatedAt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private KeySgUser userKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer watchedFlag;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCreatedAt() {
    return createdAt;
  }

  /**
   * @param createdAt createdAt or {@code null} for none
   */
  public SgCloudEpisode setCreatedAt(com.google.api.client.util.DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getEpisodeNumber() {
    return episodeNumber;
  }

  /**
   * @param episodeNumber episodeNumber or {@code null} for none
   */
  public SgCloudEpisode setEpisodeNumber(java.lang.Integer episodeNumber) {
    this.episodeNumber = episodeNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public SgCloudEpisode setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsInCollection() {
    return isInCollection;
  }

  /**
   * @param isInCollection isInCollection or {@code null} for none
   */
  public SgCloudEpisode setIsInCollection(java.lang.Boolean isInCollection) {
    this.isInCollection = isInCollection;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPlays() {
    return plays;
  }

  /**
   * @param plays plays or {@code null} for none
   */
  public SgCloudEpisode setPlays(java.lang.Integer plays) {
    this.plays = plays;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSeasonNumber() {
    return seasonNumber;
  }

  /**
   * @param seasonNumber seasonNumber or {@code null} for none
   */
  public SgCloudEpisode setSeasonNumber(java.lang.Integer seasonNumber) {
    this.seasonNumber = seasonNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getShowTmdbId() {
    return showTmdbId;
  }

  /**
   * @param showTmdbId showTmdbId or {@code null} for none
   */
  public SgCloudEpisode setShowTmdbId(java.lang.Integer showTmdbId) {
    this.showTmdbId = showTmdbId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getUpdatedAt() {
    return updatedAt;
  }

  /**
   * @param updatedAt updatedAt or {@code null} for none
   */
  public SgCloudEpisode setUpdatedAt(com.google.api.client.util.DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public KeySgUser getUserKey() {
    return userKey;
  }

  /**
   * @param userKey userKey or {@code null} for none
   */
  public SgCloudEpisode setUserKey(KeySgUser userKey) {
    this.userKey = userKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getWatchedFlag() {
    return watchedFlag;
  }

  /**
   * @param watchedFlag watchedFlag or {@code null} for none
   */
  public SgCloudEpisode setWatchedFlag(java.lang.Integer watchedFlag) {
    this.watchedFlag = watchedFlag;
    return this;
  }

  @Override
  public SgCloudEpisode set(String fieldName, Object value) {
    return (SgCloudEpisode) super.set(fieldName, value);
  }

  @Override
  public SgCloudEpisode clone() {
    return (SgCloudEpisode) super.clone();
  }

}
