/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 1969-12-31 23:59:59 UTC)
 * on 2023-08-04 at 10:37:25 UTC 
 * Modify at your own risk.
 */

package com.uwetrottmann.seriesguide.backend.lists.model;

/**
 * Model definition for SgListItem.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the lists. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SgListItem extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String listItemId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getListItemId() {
    return listItemId;
  }

  /**
   * @param listItemId listItemId or {@code null} for none
   */
  public SgListItem setListItemId(java.lang.String listItemId) {
    this.listItemId = listItemId;
    return this;
  }

  @Override
  public SgListItem set(String fieldName, Object value) {
    return (SgListItem) super.set(fieldName, value);
  }

  @Override
  public SgListItem clone() {
    return (SgListItem) super.clone();
  }

}
