// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright © 2023 Uwe Trottmann <uwe@uwetrottmann.com>
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 1969-12-31 23:59:59 UTC)
 * on 2023-08-04 at 10:37:27 UTC 
 * Modify at your own risk.
 */

package com.uwetrottmann.seriesguide.backend.movies.model;

/**
 * Model definition for MovieList.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the movies. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MovieList extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cursor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Movie> movies;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCursor() {
    return cursor;
  }

  /**
   * @param cursor cursor or {@code null} for none
   */
  public MovieList setCursor(java.lang.String cursor) {
    this.cursor = cursor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Movie> getMovies() {
    return movies;
  }

  /**
   * @param movies movies or {@code null} for none
   */
  public MovieList setMovies(java.util.List<Movie> movies) {
    this.movies = movies;
    return this;
  }

  @Override
  public MovieList set(String fieldName, Object value) {
    return (MovieList) super.set(fieldName, value);
  }

  @Override
  public MovieList clone() {
    return (MovieList) super.clone();
  }

}
