/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 1969-12-31 23:59:59 UTC)
 * on 2023-08-04 at 10:37:27 UTC 
 * Modify at your own risk.
 */

package com.uwetrottmann.seriesguide.backend.movies.model;

/**
 * Model definition for Movie.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the movies. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Movie extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime createdAt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isInCollection;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isInWatchlist;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isWatched;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer plays;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer tmdbId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime updatedAt;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCreatedAt() {
    return createdAt;
  }

  /**
   * @param createdAt createdAt or {@code null} for none
   */
  public Movie setCreatedAt(com.google.api.client.util.DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Movie setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsInCollection() {
    return isInCollection;
  }

  /**
   * @param isInCollection isInCollection or {@code null} for none
   */
  public Movie setIsInCollection(java.lang.Boolean isInCollection) {
    this.isInCollection = isInCollection;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsInWatchlist() {
    return isInWatchlist;
  }

  /**
   * @param isInWatchlist isInWatchlist or {@code null} for none
   */
  public Movie setIsInWatchlist(java.lang.Boolean isInWatchlist) {
    this.isInWatchlist = isInWatchlist;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsWatched() {
    return isWatched;
  }

  /**
   * @param isWatched isWatched or {@code null} for none
   */
  public Movie setIsWatched(java.lang.Boolean isWatched) {
    this.isWatched = isWatched;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPlays() {
    return plays;
  }

  /**
   * @param plays plays or {@code null} for none
   */
  public Movie setPlays(java.lang.Integer plays) {
    this.plays = plays;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTmdbId() {
    return tmdbId;
  }

  /**
   * @param tmdbId tmdbId or {@code null} for none
   */
  public Movie setTmdbId(java.lang.Integer tmdbId) {
    this.tmdbId = tmdbId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getUpdatedAt() {
    return updatedAt;
  }

  /**
   * @param updatedAt updatedAt or {@code null} for none
   */
  public Movie setUpdatedAt(com.google.api.client.util.DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  @Override
  public Movie set(String fieldName, Object value) {
    return (Movie) super.set(fieldName, value);
  }

  @Override
  public Movie clone() {
    return (Movie) super.clone();
  }

}
