name: Build Test Lint

# Avoid running this on the gh-pages branch
on:
  push:
    branches-ignore:
      - "gh-pages"
  pull_request:
    branches-ignore:
      - "gh-pages"
  workflow_dispatch: # Allow running manually from web UI

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    # Only run on pushes or if pull request from fork
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    permissions:
      checks: write # to publish unit test results

    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle info
        run: ./gradlew -version

      # Note: Currently no difference between flavors or debug and release
      # Note: running tests will also compile
      - name: Build and run unit tests
        run: ./gradlew :app:testPureDebugUnitTest

      - name: Test Report
        uses: dorny/test-reporter@890a17cecf52a379fc869ab770a71657660be727 # v2.1.0
        if: always() # also run if tests failed
        with:
          name: JUnit Report
          path: app/build/test-results/**/*.xml
          reporter: java-junit

  lint:
    name: Lint
    runs-on: ubuntu-latest
    # Only run on pushes or if pull request from fork
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # To speed up lint check only run for release variant and only on app module
      # Note: the app module has lintOptions.checkDependencies true, so submodules will be checked
      # Source: https://groups.google.com/forum/#!topic/lint-dev/RGTvK_uHQGQ
      # Note: running lint will also compile
      - name: Lint goog release
        run: ./gradlew :app:lintPureRelease

      - name: Lint amzn release
        if: ${{ contains(github.ref, 'release') }}
        run: ./gradlew :app:lintAmazonRelease

      - name: Upload lint reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ always() }} # also upload of lint errors
        with:
          name: Lint reports
          path: |
            app/build/reports/lint-results-pureRelease.html
            app/build/reports/lint-results-amazonRelease.html
